Repository idaka123/LyfeSync, pull requests merged in 2023-11, with the labels that each got.

#12 Canh/task management
  src/App.jsx
  src/Component/Button.jsx
  src/Component/Modal.jsx
  src/Component/SwitchButton.jsx
  src/GlobalStyle.jsx
  src/Layout/Component/Header.jsx
  src/Layout/Component/Overlay.jsx
  src/Layout/Component/Sidebar.jsx
  src/Page/Planner/Planner.jsx
  src/Page/Planner/TaskSection.jsx
  src/Page/Planner/card/GoalCard.jsx
  src/Page/Planner/card/RoutineCard.jsx
  src/Page/Planner/card/SubTask.jsx
  src/Page/Planner/card/TaskCard.jsx
  src/Page/Planner/modal/Goal.jsx
  src/Page/Planner/modal/Routine.jsx
  src/Page/Planner/modal/task.jsx
  src/Page/Setting/Appearance.jsx
  src/assets/cursor/Aim..cur
  src/assets/cursor/HVCyan_link.cur
  src/assets/cursor/KrisBackground.ani
  src/assets/cursor/KrisNormalSelect.ani
  src/assets/cursor/KrisResize.cur
  src/assets/cursor/Machete.cur
  src/assets/cursor/SPalternate.cur
  src/assets/cursor/bigcursor.cur
  src/assets/cursor/hvcy_Option_1_ds.cur
  src/assets/photos/background.json
  src/assets/photos/dark-soul.jpeg
  src/assets/photos/groot.jpeg
  src/assets/photos/sky.jpeg
  src/assets/photos/spiderman.jpeg
  src/assets/photos/sunrise.jpeg
  src/assets/photos/win-10.jpeg
  src/assets/photos/win-11.jpeg
  src/assets/photos/winxp.jpeg
Labels: enhancement

#13 clean code
  src/assets/icon.js
Labels: documentation, enhancement, good first issue

#14 update cursor for knowledge page
  src/Page/Knowledge/Knowledge.desktop.jsx
Labels: enhancement

#19 Podcast Card More handle click outside
  package-lock.json
  package.json
  src/Context/Appearance.context.jsx
  src/GlobalStyle.jsx
  src/Page/Knowledge/Components/PodcasList.jsx
  src/Page/Knowledge/Components/PodcastCard.jsx
  src/Page/Knowledge/Components/PodcastCardMore.jsx
  src/Page/Knowledge/Knowledge.desktop.jsx
  src/Page/Knowledge/Knowledge.jsx
  src/Page/Setting/Appearance.jsx
Labels: bug, enhancement

#20 rename import file
  src/Layout/default.jsx
Labels: bug

#21 fix import path asset
  src/Component/Button.jsx
  src/Component/Modal.jsx
  src/Layout/Component/Header.jsx
  src/Layout/Component/Sidebar.jsx
  src/Page/Knowledge/Components/PodcasList.jsx
  src/Page/Knowledge/Components/PodcastCard.jsx
  src/Page/Knowledge/Components/PodcastCardMore.jsx
  src/Page/Knowledge/Components/PodcastInfo.jsx
  src/Page/Knowledge/Components/PodcastPlaylist.jsx
  src/Page/Knowledge/Components/PodcastShare.jsx
  src/Page/Planner/Planner.mobile.jsx
  src/Page/Planner/card/GoalCard.jsx
  src/Page/Planner/card/RoutineCard.jsx
  src/Page/Planner/card/SubTask.jsx
  src/Page/Planner/card/TaskCard.jsx
  src/Page/Planner/modal/Goal.jsx
  src/Page/Planner/modal/Routine.jsx
  src/Page/Planner/modal/task.jsx
  src/Page/Setting/Appearance.jsx
Labels: bug

#22 fix import path
  src/Context/Modal.context.jsx
Labels: bug

#23 fix task import path
  src/Page/Planner/modal/Modal.jsx
Labels: bug

#24 update height prevent losing footer when deploy for real devices
  src/GlobalStyle.jsx
Labels: enhancement

#25 update height for real devices
  src/Component/Modal.jsx
  src/Layout/Component/Overlay.jsx
  src/Layout/Component/Sidebar.jsx
  src/Layout/default.jsx
  src/Page/Planner/card/GoalCard.jsx
  src/Page/Planner/card/RoutineCard.jsx
  src/Page/Planner/card/TaskCard.jsx
  src/Page/Setting/Appearance.jsx
  src/Page/Setting/Setting.jsx
Labels: enhancement

#26 prepare for deploy
  index.html
  src/Component/Input.jsx
  src/Component/Modal.jsx
  src/Context/Modal.context.jsx
  src/Layout/Component/Sidebar.jsx
  src/Page/Planner/Planner.json
  src/Page/Planner/Planner.jsx
  src/Page/Planner/TaskSection.jsx
  src/Page/Planner/card/SubTask.jsx
  src/Page/Planner/card/TaskCard.jsx
  src/assets/svg/index.jsx
  src/assets/svg/svg.jsx
Labels: bug, enhancement

#27 tiny file size
  src/assets/photos/dark-soul.jpeg
  src/assets/photos/forest.jpeg
  src/assets/photos/fuji.jpg
  src/assets/photos/groot.jpeg
  src/assets/photos/moon.jpeg
  src/assets/photos/sky.jpeg
  src/assets/photos/songoku.jpeg
  src/assets/photos/spiderman.jpeg
  src/assets/photos/sunrise.jpeg
  src/assets/photos/sunset.jpg
  src/assets/photos/tanjirou.jpeg
  src/assets/photos/temple.jpeg
  src/assets/photos/win-10.jpeg
  src/assets/photos/win-11.jpeg
  src/assets/photos/winxp.jpeg
Labels: enhancement

#28 Canh/prepare deploy
  src/Component/Loadding.jsx
  src/Component/Modal.jsx
  src/Context/Appearance.context.jsx
  src/GlobalStyle.jsx
  src/Page/Planner/Planner.desktop.jsx
  src/Page/Planner/Planner.jsx
  src/Page/Planner/Planner.mobile.jsx
  src/Page/Planner/TaskSection.jsx
  src/Page/Planner/card/Skeleton.jsx
  src/Page/Setting/Appearance.jsx
  src/assets/photos/background.js
  src/assets/photos/background.json
Labels: bug, enhancement

#29 update height for html
  src/GlobalStyle.jsx
  src/Page/Planner/TaskSection.jsx
Labels: bug

#30 remove status for adding routine modal
  src/Page/Planner/TaskSection.jsx
  src/Page/Planner/modal/Routine.jsx
Labels: bug, enhancement

#31 update height for testing
  src/GlobalStyle.jsx
Labels: enhancement

#32 revert update
  src/GlobalStyle.jsx
Labels: bug

#33 fix background height was not fully wrap the site
  src/Layout/default.jsx
Labels: bug

#34 update dog cursor
  src/App.jsx
  src/Component/Button.jsx
  src/Component/Modal.jsx
  src/Component/SwitchButton.jsx
  src/GlobalStyle.jsx
  src/Layout/Component/Header.jsx
  src/Layout/Component/Overlay.jsx
  src/Layout/Component/Sidebar.jsx
  src/Page/Knowledge/Knowledge.desktop.jsx
  src/Page/Planner/Planner.jsx
  src/Page/Planner/TaskSection.jsx
  src/Page/Planner/card/GoalCard.jsx
  src/Page/Planner/card/RoutineCard.jsx
  src/Page/Planner/card/SubTask.jsx
  src/Page/Planner/card/TaskCard.jsx
  src/Page/Planner/modal/Goal.jsx
  src/Page/Planner/modal/Routine.jsx
  src/Page/Planner/modal/task.jsx
  src/assets/cursor/Labradoodle.cur
  src/assets/cursor/Labrador_Retriever.cur
Labels: enhancement

#35 KnowledgeBlock Responsive
  src/Page/Knowledge/Components/Community.jsx
  src/Page/Knowledge/Components/KnowledgeBlock.jsx
  src/Page/Knowledge/Components/PodcasList.jsx
  src/Page/Knowledge/Components/PodcastCard.jsx
  src/Page/Knowledge/Components/Tip.jsx
  src/Page/Knowledge/Components/Wisdom.jsx
  src/Page/Knowledge/Knowledge.desktop.jsx
Labels: enhancement
